apiVersion: v1
kind: Pod
metadata:
  name: myapp-php
spec:
  containers:
  - name: myapp-php
  image: fabianoalcantara/myapp-php:1.0
  ports:
    - containerPort: 80
      
---

apiVersion: v1
kind: Service 
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: myapp-php 
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005   

