apiVersion: v1 
kind: PersistentVolume
metadata:
  name: local
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
   - ReadWriteOnce
  storageClassName: manual
  hostPath:
   path: /meubanco/
  
